export const gameConfig = {
    canvasWidth: 800,
    canvasHeight: 600,
    plant: {
      x: 10,
      y: 10,
      width: 50,
      height: 100,
    },
    circle: { x: 400, y: 570, radius: 20, color: "red", speed: 5 },
    treeWidth: 20,
    treeHeight: 50,
    circleRadius: 20,
    waterZone: { x: 200, y: 150, width: 400, height: 300, borderRadius: 40 },
    grassColor: "#8FBC8F",
    waterColor: "#00CED1",
    treeColor: "#228B22",
    trunkColor: "#8B4513",
    burningTreeColor: "red",
    firefighters: [
      {
        x: 600,
        y: 100,
        originalX: 600,
        originalY: 100,
        size: 30,
        velocityX: 2,
        velocityY: 2,
        color: "blue",
        canvasWidth: 800,
        canvasHeight: 600,
        groundLevel: 600,
        randomness: 0.5,
        maxSpeed: 5,
        detectionRadius: 120,
      },
      {
        x: 100,
        y: 200,
        originalX: 100,
        originalY: 200,
        size: 30,
        velocityX: -2,
        velocityY: 2,
        color: "red",
        canvasWidth: 800,
        canvasHeight: 600,
        groundLevel: 600,
        randomness: 0.5,
        maxSpeed: 7,
        detectionRadius: 120,
      },
      {
        x: 100,
        y: 500,
        originalX: 200,
        originalY: 50,
        size: 30,
        velocityX: -4,
        velocityY: 2,
        color: "green",
        canvasWidth: 800,
        canvasHeight: 600,
        groundLevel: 600,
        randomness: 0.6,
        maxSpeed: 9,
        detectionRadius: 120,
      },
    ],
    trees: [
      {
        x: 50,
        y: 300,
        burning: false,
        burningProgress: 0,
        burningStartTime: null,
        scored: false,
        velocity: 2,
        originalX: 50,
        originalY: 300,
      },
      {
        x: 700,
        y: 300,
        burning: false,
        burningProgress: 0,
        burningStartTime: null,
        scored: false,
        velocity: -2,
        originalX: 700,
        originalY: 300,
      },
    ],
  };
  